- name: Update to MacOs sequilla 15.7.4
  hosts: all
  strategy: free
  vars_prompt:
    - name: password
      prompt: What is the password?
 # vars:
 #   version: 2023.2.20f1


  tasks:

  - name: Download update
    ansible.builtin.shell: |      
      log_file /tmp/uplog.log;
      set timeout 99999999
      spawn /usr/sbin/softwareupdate -d "macOS Sequoia 15.7.4-24G517"
      expect "Password:"
      send -- "{{ password }}\r"
      expect eof
    args:
      executable: /usr/bin/expect
    #async: 60000
    #poll: 0
    become: yes
    when: 
      - ansible_facts['distribution_version'] < "15.7.4"
      - ansible_facts['distribution_version'] >= "15.0.0"

  - name: Install update
    ansible.builtin.shell: |      
      log_file /tmp/uplog.log;
      set timeout 99999999
      spawn /usr/sbin/softwareupdate -i "macOS Sequoia 15.7.4-24G517" -R --force
      expect "Password:"
      send -- "{{ password }}\r"
      expect eof
    args:
      executable: /usr/bin/expect
    async: 60000
    poll: 0
    become: yes

    when: 
      - ansible_facts['distribution_version'] < "15.7.4"
      - ansible_facts['distribution_version'] >= "15.0.0"

