- name: Install Offcie 2024
  hosts: all
  strategy: free
  vars:
    pkgname: Microsoft_365_and_Office_16.107.26032211_BusinessPro_Installer.pkg


  tasks:
  - name: Check Office
    ansible.builtin.shell:
      cmd: |
        wordVersion=$(plutil -p /Applications/Microsoft\ Word.app/Contents/Info.plist | awk '/CFBundleShortVersionString/ {print substr($3, 2, length($3)-2)}'||  grep -oE '16\.[0-9]+')

        regex="^16\.[0-9]+$"
        if [[ $wordVersion =~ $regex ]]; then
        echo "Word major version matches format"
        wordMinorVersion=$(echo $wordVersion|awk -F. '{print $2}')
        if [[ $wordMinorVersion -lt 104 ]]; then
        echo "Old version dectected: $wordVersion"
        
        exit 0
        else
        echo "Newer version detected not uninstalling"
        exit 1
        fi
        else
        echo "Word major version does not match format"
    
        exit 0
        fi
    become: yes
    args:
      executable: /bin/bash
    when:
    - ansible_facts['distribution_major_version'] > "13"


  
  - name: Copy office installer
    ansible.builtin.copy:
      src: ~/{{ pkgname }}
      dest: /tmp/{{ pkgname }}
    when:
    - ansible_facts['distribution_major_version'] > "13"

  - name: Install Office
    ansible.builtin.shell:
      cmd: installer -pkg /tmp/{{ pkgname }} -target /
    become: yes
    when:
    - ansible_facts['distribution_major_version'] > "13"
