- name: Update Adobe Apps
  hosts: all
#  vars_prompt:
#    - name: password
#      prompt: What is the password?
 # vars:
 #   version: 2023.2.20f1


  tasks:

  - name: Install updates
    ansible.builtin.shell:
      cmd: /usr/local/bin/RemoteUpdateManager
    become: yes
  


